// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dmRsZ29obG9lb3JwcnFuYmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjU5NjAsImV4cCI6MjA3MTEwMTk2MH0.OdcccS3eTk4RMSqNETbU9Zwg5slhl2lEsEU7ZeG3-jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);